version: 2.1

jobs:
  build-test:
    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout
      - restore_cache:
          key: tasklist-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: tasklist-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - run: cp target/tasklist-*.jar tasklist.jar
      - store_artifacts:
          path: tasklist.jar

workflows:
  build-test:
    jobs:
      - build-test
